# QF600 - Black Litterman
> Chapter 5  Efficient Frontier Revisited

In [1]:
import pandas as pd
import warnings
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt


warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
df_industries = pd.read_excel('./Homework_2/data/Industry_Portfolios.xlsx', index_col='Date')
df_market = pd.read_excel('./Homework_2/data/Market_Portfolio.xlsx', index_col='Date')
df = pd.merge(df_industries, df_market, left_index=True, right_index=True)

R_f = 0.13

In [8]:
excess_industries_return = df_industries.values - R_f
excess_market_return = df_market.values - R_f

risk_premiums = excess_industries_return.mean(axis=0)


- Here π is n × 1 vector of (observable) sample risk premiums, which provides noisy estimate of population risk premiums
- For simplicity, assume that Σμ = τΣ, where τ is constant In practice, often set τ = 1/m, where m is number of data points used to estimate Σ
- Reflects standard error of sample mean, when used as estimate of population mean
- Hence joint normal distribution for excess returns, expressed in terms of (observable) sample risk premiums:

In [9]:
risk_premiums

array([0.77283333, 0.60333333, 0.88283333, 1.10116667, 0.63625   ,
       0.75141667, 0.78633333, 0.65383333, 0.77716667, 0.35908333])

In [63]:
# Let P be k × n matrix of asset weights corresponding to investor’s views, and 
P = np.array([[1, 0, 0], # view 1 on asset 1
              [0,1,-1]]) # view 2 on asset 2v3
# let Q be k × 1 vector of expected returns corresponding to investor’s views
Q = np.array([0.05, 0.01]).T
# Market equilibrium excess returns
pi = np.array([0.05, 0.03, 0.04]).T
# Covariance matrix of asset returns
Sigma = np.array([[0.1, 0.05, 0.02],
                  [0.05, 0.08, 0.03],
                  [0.02, 0.03, 0.06]])
# Investor's confidence level
tau = 0.025
# Uncertainty in the views
Omega = np.diag([0.0001, 0.0001])


In [64]:
P.shape, Q.shape

((2, 3), (2,))

In [70]:
pi_cap = pi + tau * Sigma @ P.T @ np.linalg.inv(tau * P @ Sigma @ P.T + Omega) @ (Q - P @ pi) 
M = np.linalg.inv(np.linalg.inv(tau * Sigma) + np.dot(np.dot(P.T, np.linalg.inv(Omega)), P))

In [71]:
pi_cap, M

(array([0.05030628, 0.03944359, 0.03050536]),
 array([[9.57120980e-05, 3.44563553e-05, 3.29249617e-05],
        [3.44563553e-05, 9.79070955e-04, 9.31852986e-04],
        [3.29249617e-05, 9.31852986e-04, 9.79326187e-04]]))