# State Prices

- state prices
- call option pricing

In [14]:
import pandas as pd
import numpy as np

# Create a DataFrame from the data
df = pd.DataFrame({
    "State":    ["Good", "Normal", "Bad"],
    "Phys Prob":[0.3, 0.5, 0.2],
    "Stock A":  [75, 55, 20],
    "Stock B":  [60, 50, 40]
})

df_transposed = df.transpose()
df_transposed.to_csv("State_Prices.csv")

In [15]:
df

State  Phys Prob  Stock A  Stock B
0    Good        0.3       75       60
1  Normal        0.5       55       50
2     Bad        0.2       20       40

In [16]:
df = pd.read_csv('State_Prices.csv', header=1)
df.set_index('State', inplace=True)

In [17]:
# let X be k × n matrix that shows all possible outcomes of assets
X = df.values.T[:,1:]       # remove probability row

# Create a column of 1s with the same number of rows as the data array
ones_column = np.ones((X.shape[0], 1))

# Concatenate the column of 1s with the data array horizontally
X = np.hstack((ones_column, X))

X

array([[ 1., 75., 60.],
       [ 1., 55., 50.],
       [ 1., 20., 40.]])

In [18]:
# define initial prices
R_f = 1.1
Initial_px_A = 45
Initial_px_B = 45


P = np.array([1/R_f, Initial_px_A, Initial_px_B])
P

array([ 0.90909091, 45.        , 45.        ])

State prices $p_s = \vec{P}' X^{-1}$

In [19]:
# get vector of state prices
vector_state_prices = P.T@np.linalg.inv(X)
vector_state_prices

array([0.22727273, 0.40909091, 0.27272727])

$p_s$ is known as state price for state s, which represents initial value of receiving final payoff of one in state s.

Risk Neutral porb is equal to risk-free by state prices
$\tilde{\pi}_s = R_f \times p_s$

In [20]:
# get vector of risk-neutral probs
risk_neutral_probs = vector_state_prices * R_f
risk_neutral_probs

array([0.25, 0.45, 0.3 ])

In [21]:
P.T@np.linalg.inv(X)

array([0.22727273, 0.40909091, 0.27272727])

Instead of using state prices. also can use  the equation directly

$P_Y = \vec{P}' X^{-1} \vec{Y}$ 

where $P_Y$ is initial prices, $\vec{Y}$ is target final outcome

---
#### Option to buy one share of Stock A and one share of Stock B for 100

In [22]:
"""

for asigning different stock quantities in the final pay off for the function

"""

# Create a quantity array
# quantities = np.array([1, 2, 0])

# # Reshape the quantities array to match the number of columns in the main array
# quantities = quantities.reshape(1, -1)

# # Multiply each column of the array by the corresponding element in the quantities array
# scaled_arr = X * quantities

# print(scaled_arr)

'\n\nfor asigning different stock quantities in the final pay off for the function\n\n'

In [23]:
# Sum final price of 1 share of stock A and 1 share of stock B
(X[:,1:].sum(axis=1))

array([135., 105.,  60.])

In [24]:
# call option strike
K =100
call_payoff = np.clip(X[:, 1:].sum(axis=1) - K, 0, None)
call_payoff

array([35.,  5.,  0.])

In [25]:
# Method 1
expected_final_payoff = (vector_state_prices * call_payoff).sum()  # first element times first element of both arrays, then sum
initial_px_option = expected_final_payoff
print(initial_px_option)

# Method 2
expected_final_payoff_2 = (risk_neutral_probs * call_payoff).sum()
initial_px_option_2 = expected_final_payoff_2 / R_f
print(initial_px_option_2)

10.000000000000027
10.000000000000025


when getting risk neutral price.

- use P measure then discount by pricing kernel
- use Q measure then discount by risk-free rate